### ISSUE TITLE
What other programming languages do You tried and why chosen JavaScript over them?

### ISSUE THREAD

**Issue by drKraken** [arthurvr/ama#10]

**Comment by arthurvr** [comment]
> What other programming languages do You tried

 Haskell, Swift, Rust, Python, PHP :no_entry_sign: and a little of Ruby.

I've always been willing to do more OSS around Rust and Haskell. One day,  I guess.

> why chosen JavaScript over them? 

I like JavaScript but I didn't really "choose" JavaScript. It's just a good fit for what I'm doing at the moment. Also, there's not much of a choice to build client-side things :wink: 

I also really like its community.
