### ISSUE TITLE
Linux vs OS X 

### ISSUE THREAD

**Issue by harshasrinivas** [arthurvr/ama#15]
:smile:

**Comment by arthurvr** [comment]
Ugh. That's a super difficult question to answer. It all boils down to personal opinions at the end.

I pretty much spend fifty-fifty of my time on both. The only fact that Linux is open-source makes me willing to answer that, though. On the other hand I'm really into Apple's visual design decisions.

Sorry for not having a real answer for you. If you'd ask me for my purely my developer point of view, I'd probably answer Linux. But at the end you end up doing a whole lot of non-developer tasks every day.

I'm already happy when I don't have to work on windows :tada:

**Comment by harshasrinivas** [comment]
haha cool! Thanks! :sweat_smile:
