### ISSUE TITLE
how does your iphone homescreen look like?

### ISSUE THREAD

**Issue by robbbz** [arthurvr/ama#18]
Just like with @sindresorhus I want a screenshot. Thanks. https://github.com/sindresorhus/ama/issues/64

**Comment by arthurvr** [comment]
*Unfortunately I don't care too much about how my homescreen looks. Some apps in there are rarely used, in fact. I just use the search feature to open apps. Lolz. I just noticed that @sindresorhus also has a `lolz` folder.*

![img_4538](https://cloud.githubusercontent.com/assets/6025224/8533173/7fd0b25a-2433-11e5-96c6-6c2d9f10e4a4.PNG)
