### ISSUE TITLE
how fast do you type?

### ISSUE THREAD

**Issue by robbbz** [arthurvr/ama#24]
I asked this to @sindresorhus as well: https://github.com/sindresorhus/ama/issues/128.

**Comment by arthurvr** [comment]
I'm always somewhere between 80 and 90. Not really good :crying_cat_face: 

But it doesn't make much sense. If you feel like you're not productive/fast enough, you should rather try to optimize on other points. Many people waste  an awful lot of time when scaffolding an app, simply type too much code, don't know their editor well, ...

Also keep in mind that the important thing is what you're typing not how fast you type it.
