### ISSUE TITLE
How did you make your display picture?

### ISSUE THREAD

**Issue by alexbooker** [arthurvr/ama#26]
Hey, @arthurvr,

Congratulations on joining the @yeoman team! 

My question is: How did you make your display picture? If someone else made it, who? I really like it and would :heart: something similar.

**Comment by arthurvr** [comment]
Excellent question. Reminds me that I need to change my avatar one day. With my real face this time.

I believe it was with an iPhone app called [iMadeFace](https://itunes.apple.com/us/app/imadeface/id582560267?mt=8). It was popular really long ago and I just never changed my avatar :)

Thanks for the question!

**Comment by phanan** [comment]
Shit someone took my question!
