### ISSUE TITLE
How did you become involved to so large number of open-source projects?

### ISSUE THREAD

**Issue by drKraken** [arthurvr/ama#3]

**Comment by arthurvr** [comment]
I started doing open source by contributing to HTML5 Boilerplate. I actually never expected them to accept my contributions, but they did! :smile:

And I stayed opening PRs, some better than the others, and bit and bit I got my feed wet in OSS.

A few months later I was complaining on IRC about a PR of mine to a jQuery repo staying open for really long. They told me they needed some help writing/maintaining documentation. I spent a few weekends trying to get their issue count down, it worked out, and short after that was I invited to the team :tada: 

After that I simply stayed participating in discussions that interest me and got involved in more and more awesome open-source organisations and met awesome people.

Thanks for the awesome question!

**Comment by insanehong** [comment]
:+1:
