### ISSUE TITLE
What is your workflow, extensions and etc?

### ISSUE THREAD

**Issue by tunnckoCore** [arthurvr/ama#38]
Browser extensions, editor, scaffollder/generator and etc stuff.

**Comment by arthurvr** [comment]
> Browser extensions,

Not that much, in fact. I've got Hangouts, Pocket, Livereload, [github-linker](https://github.com/github-linker/chrome-extension), [GitHub Hide Files](https://chrome.google.com/webstore/detail/github-hide-files/lpnakhpaodhdkleejaehlapdhbgjbddp), [GitHub tab size](https://chrome.google.com/webstore/detail/github-tab-size/ofjbgncegkdemndciafljngjbdpfmbkn), [GitHub highlight selected](https://chrome.google.com/webstore/detail/github-highlight-selected/lhiklbgjcblimmjjflobpncgihagcmbj), [GitHub Mate](https://chrome.google.com/webstore/detail/github-mate/baggcehellihkglakjnmnhpnjmkbmpkf?utm_source=chrome-ntp-icon), [Pages2repo](https://chrome.google.com/webstore/detail/pages2repo/afnogakjnebbgcbjkgmhaccljfejeflh).

Also I use [timeline-url](https://github.com/ChromeDevTools/timeline-url) extensively. It's a package Paul Irish and I built to make it easy to share devtools timelines.

I'm a tab-monster so I use [kill-tabs](https://github.com/sindresorhus/kill-tabs) a lot.

> scaffollder/generator

I use Yeoman a lot. Mainly [generator-wbp](https://github.com/silvenon/generator-wbp), [generator-nm](https://github.com/sindresorhus/generator-nm/), [generator-node](https://github.com/yeoman/generator-node), [generator-polymer](https://github.com/yeoman/generator-polymer) and [generator-mobile](https://github.com/yeoman/generator-mobile). That are the ones I use most often but there's a good generator for everything out there. And if there isn't, it's always super easy to build one :tada: 

> editor

:heart: Vim and tmux. See https://github.com/arthurvr/ama/issues/5#issuecomment-118173298. I also write iPhone apps once upon a time, so xcode is unavoidable. Though I try to do most of the actual text editing in Vim.
