### ISSUE TITLE
What do you think about upcoming Gulp4 and core behind it?

### ISSUE THREAD

**Issue by tunnckoCore** [arthurvr/ama#39]
Core behind it like `async-done`, `undertaker`, `bach`

**Comment by arthurvr** [comment]
I haven't written a whole build system with Gulp 4 yet, so I'm not the right one to judge it for the time being. In general I like the direction it's going, there are some great improvements. It's still my favourite build tool.

Personally I write Node.js daily, so Gulpfiles feel second nature to me. I wonder, though, how it feels like for front-end developers/designers who aren't familiar with any node. Though I like Gulp, I still think Grunt's approach to configurations might have been easier for many people. Not really sure.
