### ISSUE TITLE
How do you stay up-to-date in web-development

### ISSUE THREAD

**Issue by drKraken** [arthurvr/ama#4]
Maybe, some podcasts, websites that you visit.

**Comment by arthurvr** [comment]
In my opinion, the best way to keep up to date with this super-fast moving community is by being actively involved with it.  

I mostly get to know new technologies by listening to podcasts, reading blogs and doing open source. When I feel like something specific interests me, I go lookup a site or article. If it still interests me I'll probably go read a book and simply try things out.

One day I need to do a write-up about what podcasts I listen too (quite a bunch of podcasts that are). I'm going to keep this issue open as a reminder.

*Thanks!*

**Comment by drKraken** [comment]
Cool, also i saw you Goodread's account and seems like you read a great number of books about web. So wondering what is you favorite one-three books about js ?

**Comment by arthurvr** [comment]
@drKraken I used to read quite a bit of books yeah. Some really good ones I enjoyed very much:

* [The Pragmatic Programmer](https://pragprog.com/the-pragmatic-programmer)
* [Learn You a Haskell for Great Good](http://learnyouahaskell.com/chapters) *(I, at the moment, don't do much haskell but Haskell did really change my mind and way of thinking in many good ways)*
* [Don't Make Me Think](http://www.amazon.com/Dont-Make-Me-Think-Usability/dp/0321344758)
* [Build APIs You Won't Hate](https://leanpub.com/build-apis-you-wont-hate?a=2Z3GI0ziH6FA7gjNePqgrz)
* [Clean Code](http://www.amazon.com/gp/product/0132350882/ref=as_li_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=0132350882&linkCode=as2&tag=nett02-20&linkId=TJNQOU5QKV5LJLN5)
* [JavaScript: The Good Parts](http://shop.oreilly.com/product/9780596517748.do) *(It's a good book to read and touches some things every JavaScript programmer should be aware of, although, don't get too crocky-fied)*

There's probably way more than that but I really learned a bunch by reading these. Some of them fundamentally changed the way I think about code and programming.

**Comment by sirodoht** [comment]
@arthurvr You mention JS The Good Parts, but also say *don't get to crocky-fied*. After reading it I think I may have, so what would you propose for getting familiar with the current JS ecosystem and its best/most used practices?

**Comment by sotojuan** [comment]
@sirodoht I suggest You Don't Know JS series by Kyle Simpson.

**Comment by arthurvr** [comment]
Closing this issue as somebody asked another question about podcasts: https://github.com/arthurvr/ama/issues/23.

@sirodoht Crockford has really strong opinions, but opinions are *personal*. He tends to go a little [too strong](https://www.youtube.com/watch?v=eGArABpLy0k) about those. Because of that we end up with [waaayyy to long](https://github.com/twbs/bootstrap/issues/3057#issuecomment-5135512) discussions which really don't make sense. Don't do that. Build your own opinion and don't spend time bike shedding.
