### ISSUE TITLE
Have you any idea why...?

### ISSUE THREAD

**Issue by tunnckoCore** [arthurvr/ama#40]
@sindresorhus blocked me everywhere? And left our orgs?

It's absolutely tragedy in that AMA pick that I cant fork/mention/star/watch/comment around him lol.

You can ping me back at https://github.com/tunnckoCore/messages which is my AMA thing.

**Comment by arthurvr** [comment]
I honestly have no idea.

> And left our orgs?

I can only speak for myself here, but I left regexps too. I prefer to be the [BDFL](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life) on my modules and don't see the value of an org like that.

**Comment by tunnckoCore** [comment]
> I can only speak for myself here, but I left regexps too. I prefer to be the BDFL on my modules and don't see the value of an org like that.

Huh, strange. Is im missing something with that org?

> I prefer to be the BDFL on my modules

You will, why you think you won't?

> don't see the value of an org like that.

Then why we invest and put so much work and time and so much libs in the entire node/npm ecosystem? If we will so closed, why we are talkin we are "open source", open mind, evangelists and etc.?

The value is to be centralized community with help, resources, recipes and index with soooo much regexes available in the world in so many langs. Value is to be with great centralized maintenance and big team which know what does and how to do it better.
You can still control your libs. We can consider some rules to dont merge/publish and etc, that's why I created ["General discussion"](https://github.com/regexps/meta/issues/16) and trying to move the project to some path.
