### ISSUE TITLE
What sort of games do you like to play?

### ISSUE THREAD

**Issue by blainsmith** [arthurvr/ama#41]
This includes video games, board, games, card games, etc.

**Comment by arthurvr** [comment]
I don't game that much. The only gaming I really do are fun little things on my phone to play when I have 5 spare minutes. Currently I'm into [Doctor Who: Legacy](https://itunes.apple.com/us/app/doctor-who-legacy/id737628981?mt=8). I've been willing to get into some of those cool board games but never got to it.
