### ISSUE TITLE
What's your favorite movie or TV show?

### ISSUE THREAD

**Issue by silvenon** [arthurvr/ama#42]

**Comment by arthurvr** [comment]
I'm a whovian. Anything you'd like to know more than I answered in https://github.com/arthurvr/ama/issues/2?

**Comment by silvenon** [comment]
I searched for "movie", but that issue didn't come up. I it doesn't do partial matching, my bad. Thanks! :+1:

**Comment by arthurvr** [comment]
No problem :p
