### ISSUE TITLE
Why did you block tunnckoCore??

### ISSUE THREAD

**Issue by taplzr** [arthurvr/ama#44]
im just interested why you blocked him

and do you know why @sindresorhus blocked him?

do you block people often?

**Comment by arthurvr** [comment]
> im just interested why you blocked him

The only thing you ever did is asking why he's blocked. Yeah right.


> and do you know why @sindresorhus blocked him?

Already answered in https://github.com/arthurvr/ama/issues/40.


> do you block people often?

Yes.
