### ISSUE TITLE
At what age you started to learn programming?

### ISSUE THREAD

**Issue by drKraken** [arthurvr/ama#7]

**Comment by arthurvr** [comment]
I got into HTML when I was about 8 years old. Just toying though. Nothing serious. My first lines of more serious code were ruby and then I fell in love with JavaScript. Not sure but I should've been 10 or 11.

Thanks for the question. Keep 'em coming.

**Comment by HugoGiraudel** [comment]
> I got into HTML when I was about 8 years old

That's impressive though. :)
