### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by kentcdodds** [arthurvr/ama#73]
I've seen you help out @sindresorhus on a lot of projects and I know that you've been a great contributor to many more projects. I was browsing around and landed on your profile page and was really surprised to see this:

<img width="767" alt="screen shot 2016-02-27 at 10 22 25 pm" src="https://cloud.githubusercontent.com/assets/1500684/13377646/b08f54ce-dda0-11e5-98ea-54bf5e63d04c.png">

Just curious to know what happened. Did you burn out? Just decide to focus on other areas of your life?

**Comment by arthurvr** [comment]
Yeah. I wouldn't really call it a burn out. Just had lots of personal stuff to deal with last year, and I had a very busy school year so I decided to put some OSS stuff away for a while. I'm gonna have more time to spend on open source again soon though :) 

I always responded to all the urgent stuff, and I don't actively maintain any big projects on my own so I don't think it really hurt anything.  I have lots of stuff to catch up on now though. Thanks for thinking about me! :D

**Comment by sindresorhus** [comment]
@arthurvr Glad to hear you're alright :)

**Comment by mischah** [comment]
Welcome back 🎉
