### ISSUE TITLE
If there are only 3 tools that you able to use, what will you choose?

### ISSUE THREAD

**Issue by drKraken** [arthurvr/ama#8]

**Comment by arthurvr** [comment]
To build webapps you mean? Or something else?

**Comment by drKraken** [comment]
@arthurvr yes

**Comment by arthurvr** [comment]
Wow. Good question. :clap: Really difficult to answer. It would probably be a terminal (and thus also vim),  Yeoman and a browser.

I should probably come up with a better answer. Let me think about this one for a few hours.

**Comment by arthurvr** [comment]
Hmm. No. In fact that the only answer I really have.

Explaining why I need a browser or a text editor to develop a webapp would be kind useless. Feel free to ask any more specific questions. I don't really know what to say more than the things I listed.
